# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Update or install Werkzeug
RUN pip install --upgrade Werkzeug

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable
ENV FLASK_APP=smarthomecontrollermicroservice.py

# Run the Smart Home Controller microservice
CMD ["flask", "run", "--host=0.0.0.0"]